"""empty message

Revision ID: 4248c71c26e5
Revises: 23d817b7980c
Create Date: 2022-08-05 21:38:57.573310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4248c71c26e5'
down_revision = '23d817b7980c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrizes_cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_disc', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_disc'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cursos', 'id_depto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'cursos', 'departamentos', ['id_depto'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.alter_column('cursos', 'id_depto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('matrizes_cursos')
    # ### end Alembic commands ###
