"""empty message

Revision ID: 888910ab4181
Revises: 4248c71c26e5
Create Date: 2022-08-05 21:43:04.351661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888910ab4181'
down_revision = '4248c71c26e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alunos', 'id_curso',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'alunos', 'cursos', ['id_curso'], ['id'])
    op.add_column('matriculas', sa.Column('semestre', sa.Integer(), nullable=False))
    op.alter_column('matriculas', 'id_disc',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matriculas', 'id_aluno',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'matriculas', 'alunos', ['id_aluno'], ['id'])
    op.create_foreign_key(None, 'matriculas', 'disciplinas', ['id_disc'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matriculas', type_='foreignkey')
    op.drop_constraint(None, 'matriculas', type_='foreignkey')
    op.alter_column('matriculas', 'id_aluno',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matriculas', 'id_disc',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('matriculas', 'semestre')
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.alter_column('alunos', 'id_curso',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
