"""empty message

Revision ID: 959021c9a31b
Revises: 542a6ae0e396
Create Date: 2022-08-02 21:54:52.900998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959021c9a31b'
down_revision = '542a6ae0e396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devtechs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tech', sa.Integer(), nullable=False),
    sa.Column('id_dev', sa.Integer(), nullable=False),
    sa.Column('is_main_tech', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_dev'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['id_tech'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devtechs')
    # ### end Alembic commands ###
